name: Docker Build voting

on:
  workflow_dispatch:
  push:
    tags:
      - v*
    branches:
      - main

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: buildpacks/github-actions/setup-pack@v4.8.1

      - name: Extract metadata for the Docker image
        id: meta
        uses: docker/metadata-action@57396166ad8aefe6098280995947635806a0e6ea
        with:
          images: ghcr.io/beer4peer/voting

      - name: Build Documentation
        run: mkdocs build --no-directory-urls

      - id: build
        name: Build and Publish container
        env:
          FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
          HEROKU_PHP_PLATFORM_REPOSITORIES: https://heroku-php-extensions.s3.amazonaws.com/dist-heroku-20-stable/packages.json
          APP_ENV: production
        run: |
          pack build ghcr.io/beer4peer/voting \
          --tag ghcr.io/beer4peer/voting:${{ github.ref_name }}-$(git rev-parse --short HEAD)-$(date +%s) \
          --tag $(echo "${{ steps.meta.outputs.tags }}" | xargs | sed 's/ / --tag /') \
          --env "HEROKU_PHP_PLATFORM_REPOSITORIES" \
          --env "FONTAWESOME_NPM_AUTH_TOKEN" \
          --env "APP_ENV" \
          -B heroku/buildpacks:20 \
          -b heroku/nodejs \
          -b heroku/php \
          --publish
